FROM python:3.6.4

RUN apt-get update -yqq \
  && apt-get install -yqq --no-install-recommends \
    netcat \
  && apt-get -q clean

ADD . /app
WORKDIR /app
RUN pip install -r requirements.txt
CMD ["./entrypoint.sh", "users-db"]